/*
 * SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * xemantic-typescript-compiler - a conformant TypeScript compiler and type
 * checker that runs on JVM, native, and WebAssembly
 * Copyright (C) 2026 Kazimierz Pogoda / Xemantic
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, this file contains Helper Code covered by the
 * xemantic-typescript-compiler Output Exception; additional permissions
 * are granted as described in the file LICENSE-EXCEPTION.
 */

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("xemantic-typescript-compiler.convention")
}

base {
    archivesName = project.name
}

// (TSGO.1) THE PORTER (owner decision 2026-10-06, docs/tsgo-port-plan.md,
// contract docs/goport-design.md, notes docs/goport-lowering.md).
//
// Reads the typed Go IR written by `goport-extract/` (build/goport/ir/*.json —
// regenerate it with Go, see docs/goport-ir.md), lowers it mechanically into
// Kotlin, splices the hash-pinned hand ports from `overrides/`, and writes
// `xemantic-typescript-compiler-tsgo/src/commonMain/kotlin/gen/`. A dev tool:
// JVM only, never published, and nothing else in the build depends on it.
//
//   ./gradlew :xemantic-typescript-compiler-goport:port
kotlin {

    jvm()

    sourceSets {

        jvmMain {
            dependencies {
                implementation(libs.kotlinx.serialization.json)
            }
        }

        jvmTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.xemantic.kotlin.test)
            }
        }

    }

}

tasks.register<JavaExec>("port") {
    group = "goport"
    description = "Lowers build/goport/ir into -tsgo's generated Kotlin (src/commonMain/kotlin/gen)."
    val jvmMain = kotlin.jvm().compilations.getByName("main")
    dependsOn(jvmMain.compileTaskProvider)
    classpath = files(jvmMain.output.allOutputs, jvmMain.runtimeDependencyFiles)
    mainClass.set("com.xemantic.typescript.goport.MainKt")
    maxHeapSize = "6g"
    val root = rootDir
    args(
        "--ir", root.resolve("build/goport/ir").absolutePath,
        "--overrides", projectDir.resolve("overrides").absolutePath,
        "--renames", projectDir.resolve("renames.txt").absolutePath,
        "--refuse", projectDir.resolve("refuse.txt").absolutePath,
        "--out", root.resolve("xemantic-typescript-compiler-tsgo/src/commonMain/kotlin/gen").absolutePath,
        "--tsgo", root.resolve("typescript-go-repo").absolutePath,
    )
    // The output is checked in and the inputs live outside Gradle's view (the
    // IR is regenerated by Go), so the task always runs.
    outputs.upToDateWhen { false }
}
