/*
 * SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * xemantic-typescript-compiler - a conformant TypeScript compiler and type
 * checker that runs on JVM, native, and WebAssembly
 * Copyright (C) 2026 Kazimierz Pogoda / Xemantic
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, this file contains Helper Code covered by the
 * xemantic-typescript-compiler Output Exception; additional permissions
 * are granted as described in the file LICENSE-EXCEPTION.
 */

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("xemantic-typescript-compiler.convention")
}

base {
    archivesName = project.name
}

// (TSGO.1) THE tsgo PORT (owner decision 2026-10-06, docs/tsgo-port-plan.md).
//
// `src/commonMain/kotlin/runtime` is the hand-written Go runtime the generated
// code calls (`GoSlice`, `GoMap`, `GoPtr`, byte strings, panics, tuples), and
// `src/commonMain/kotlin/go` holds the hand-written shims for the Go standard
// library and the non-tsgo modules tsgo imports. Their API is the lowering's
// contract: docs/goport-runtime.md. `src/commonMain/kotlin/gen` (generated by
// `-goport`, never edited by hand) arrives later.
//
// Kotlin stdlib only and no `java.*` in commonMain: the port must stay
// Kotlin/Native-compatible (docs/goport-design.md § 1). JVM is the only target
// exercised during the spike. Licence: AGPL-3.0-only with the output exception
// for the modified work; tsgo's own `LICENSE` and `NOTICE.txt` ship unchanged
// beside this file (D2).
kotlin {

    jvm()

    // (TSGO.6) Kotlin/Native, opt-in exactly as -core's: only with `-PenableNativeTargets=true`, so a
    // plain JVM build never sees it. Native builds run ALONE under CLAUDE.md's memory protocol (zero
    // swap; K/N compiles inside the GRADLE daemon). The executable checks one tsconfig project
    // (`nativeMain/kotlin/NativeCheckMain.kt`), the end-to-end probe against the JVM port and tsgo.
    if (project.findProperty("enableNativeTargets") == "true") {
        linuxX64 {
            binaries.executable {
                entryPoint = "com.xemantic.typescript.tsgo.nativeCheckMain"
                // `-PtsgoNativeGcLogs=true`: the runtime's GC epochs on stderr (how (TSGO.6) found the stalls).
                if (project.findProperty("tsgoNativeGcLogs") == "true") freeCompilerArgs += "-Xruntime-logs=gc=info"
            }
        }
    }

    sourceSets {

        commonTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.xemantic.kotlin.test)
            }
        }

        // TEST SCOPE ONLY: ParseBenchMain compares the port's parser with -core's (the
        // (TSGO.1) throughput gate, docs/goport-perf.md). commonMain must never depend on -core.
        jvmTest {
            dependencies {
                implementation(project(":xemantic-typescript-compiler-core"))
            }
        }

    }

}

// The (TSGO.1) gate is selected by environment variables (OracleParityTest, TsgoPinTest); make them
// test inputs, or a run with TSGO_ORACLE=bound after a plain run is UP-TO-DATE and measures nothing.
tasks.withType<Test>().configureEach {
    for (v in listOf(
        "TSGO_ORACLE", "TSGO_ORACLE_LIMIT", "TSGO_ORACLE_SOURCE", "TSGO_ORACLE_REAL_HASH", "TSGO_ORACLE_DIAGS",
        "TSGO_DIAG", "TSGO_DIAG_LIMIT", "TSGO_DIAG_FILTER", "TSGO_DIAG_INJECT", "TSGO_SNIPPET",
        "TSGO_EMIT", "TSGO_EMIT_LIMIT", "TSGO_EMIT_FILTER", "TSGO_EMIT_INJECT", "TSGO_EMIT_THREADS",
        "TSGO_API", "TSGO_API_LIMIT", "TSGO_API_FILTER", "TSGO_API_INJECT",
        "TSGO_LS", "TSGO_LS_LIMIT", "TSGO_LS_FILTER", "TSGO_LS_INJECT",
        "TSGO_CLI", "TSGO_CLI_FILTER", "TSGO_CLI_INJECT",
    )) {
        inputs.property(v, providers.environmentVariable(v).orElse(""))
    }
    // The (TSGO.2) diagnostics differential (DiagParityTest) builds a Program per configuration; the
    // bundled libs alone are ~100 MB of AST. Opt-in larger heap, so a plain run keeps Gradle's default.
    providers.environmentVariable("TSGO_TEST_HEAP").orNull?.let { maxHeapSize = it }
}

// (TSGO.6) THE GraalVM IMAGE OF THE PORTED tsc COMMAND LINE ((TSGO.5)'s `TsgoMain`), the counterpart of
// -cli's `nativeImage` (whose comments carry the rationale; this one is that task with the port's entry):
//
//   ./gradlew :xemantic-typescript-compiler-tsgo:nativeImage -PgraalvmHome=tools/graalvm-25
//   ./gradlew :…-tsgo:nativeImage -PnativeImageArgs="--pgo-instrument" -PnativeImageOutput=xtsc-tsgo-instrumented
//
// THE GC IS G1 BY DEFAULT, AND ITS HEAP LIMIT IS RAISED TO 80% OF RAM (measured 2026-10-09, Oracle GraalVM 25.0.4,
// tsc's compiler profile, 65 rows byte-identical in every arm): the default serial collector is single-threaded
// and stopped every goroutine for ~6.4 s of an 8.8 s check (1.76 s for tsgo); G1 runs it in 2.9 s. But G1's
// default limit is 25% of RAM (`-R:MaxRAMPercentage=25`, serial's is 80%), and type-fest needs ~9.7 GB: at the
// default the image ran out of memory INSIDE goroutines and hung (now a fatal exit, `goSpawn`). G1 is Oracle
// GraalVM only — GraalVM Community Edition builds with `-PnativeImageGc=serial`.
//
// Not wired into `build`/`check` (needs GraalVM + a C toolchain). Builds run ALONE under CLAUDE.md's memory
// protocol: the builder is a separate JVM of `-PnativeImageHeap` (default 8g — the port's closed world is
// ~4,850 classes, over twice -core's) outside every Gradle heap, on a box with zero swap.
val tsgoNativeImageMainClass = "com.xemantic.typescript.tsgo.cli.TsgoMainKt"

tasks.register("nativeImage") {
    group = "build"
    description = "Ahead-of-time compiles the ported tsc CLI into a native executable (needs GraalVM + a C toolchain)."

    val jvmMain = kotlin.targets.getByName("jvm").compilations.getByName("main")
    dependsOn(jvmMain.compileTaskProvider)
    val classpathFiles = files(jvmMain.output.allOutputs, jvmMain.runtimeDependencyFiles)
    inputs.files(classpathFiles)
    inputs.property("mainClass", tsgoNativeImageMainClass)

    // A relative -PgraalvmHome resolves against the ROOT project, never the daemon's cwd (CLAUDE.md).
    val graalHome = ((project.findProperty("graalvmHome") as String?) ?: System.getenv("GRAALVM_HOME"))
        ?.let { rootDir.resolve(it) }
    val builderHeap = (project.findProperty("nativeImageHeap") as String?) ?: "8g"
    val extraArgs = (project.findProperty("nativeImageArgs") as String?)
        ?.split(" ", "\t", "\n")?.filter { it.isNotBlank() } ?: emptyList()
    val gcArgs = when (val gc = (project.findProperty("nativeImageGc") as String?) ?: "G1") {
        "G1" -> listOf("--gc=G1", "-R:MaxRAMPercentage=80")
        "serial" -> listOf("--gc=serial")
        else -> error("-PnativeImageGc must be G1 or serial, not '$gc'")
    }
    val outputName = (project.findProperty("nativeImageOutput") as String?) ?: "xtsc-tsgo"
    inputs.property("nativeImageArgs", extraArgs)
    inputs.property("gcArgs", gcArgs)
    inputs.property("outputName", outputName)
    val outputDir = layout.buildDirectory.dir("native")
    outputs.file(outputDir.map { it.file(outputName) })

    doLast {
        val fromHome = graalHome?.resolve("bin/native-image")
        val onPath = System.getenv("PATH")?.split(File.pathSeparator)
            ?.map { File(it).resolve("native-image") }?.firstOrNull { it.canExecute() }
        val tool = when {
            fromHome != null && fromHome.canExecute() -> fromHome.absolutePath
            fromHome != null -> error("native-image not found at $fromHome — is it a GraalVM JDK?")
            onPath != null -> onPath.absolutePath
            else -> error(
                "native-image not found. Put a GraalVM JDK's bin/ on PATH, set GRAALVM_HOME, or pass " +
                    "-PgraalvmHome=/path/to/graalvm. A C toolchain (gcc, binutils, libc headers, zlib) is also required."
            )
        }
        val out = outputDir.get().asFile.also { it.mkdirs() }
        val binary = out.resolve(outputName)
        val cmd = listOf(
            tool,
            "-cp", classpathFiles.joinToString(File.pathSeparator) { it.absolutePath },
            "-o", binary.absolutePath,
            "--no-fallback",
            "-J-Xmx$builderHeap",
        ) + gcArgs + extraArgs + tsgoNativeImageMainClass
        val exitCode = ProcessBuilder(cmd).directory(projectDir).inheritIO().start().waitFor()
        check(exitCode == 0) { "native-image failed (exit $exitCode)" }
        logger.lifecycle("Native executable: $binary")
    }
}
