/*
 * SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * xemantic-typescript-compiler - a conformant TypeScript compiler and type
 * checker that runs on JVM, native, and WebAssembly
 * Copyright (C) 2026 Kazimierz Pogoda / Xemantic
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, this file contains Helper Code covered by the
 * xemantic-typescript-compiler Output Exception; additional permissions
 * are granted as described in the file LICENSE-EXCEPTION.
 */

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("xemantic-typescript-compiler.convention")
}

base {
    archivesName = project.name
}

// (TSGO.1) THE tsgo PORT (owner decision 2026-10-06, docs/tsgo-port-plan.md).
//
// `src/commonMain/kotlin/runtime` is the hand-written Go runtime the generated
// code calls (`GoSlice`, `GoMap`, `GoPtr`, byte strings, panics, tuples), and
// `src/commonMain/kotlin/go` holds the hand-written shims for the Go standard
// library and the non-tsgo modules tsgo imports. Their API is the lowering's
// contract: docs/goport-runtime.md. `src/commonMain/kotlin/gen` (generated by
// `-goport`, never edited by hand) arrives later.
//
// Kotlin stdlib only and no `java.*` in commonMain: the port must stay
// Kotlin/Native-compatible (docs/goport-design.md § 1). JVM is the only target
// exercised during the spike. Licence: AGPL-3.0-only with the output exception
// for the modified work; tsgo's own `LICENSE` and `NOTICE.txt` ship unchanged
// beside this file (D2).
kotlin {

    jvm()

    sourceSets {

        commonTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.xemantic.kotlin.test)
            }
        }

        // TEST SCOPE ONLY: ParseBenchMain compares the port's parser with -core's (the
        // (TSGO.1) throughput gate, docs/goport-perf.md). commonMain must never depend on -core.
        jvmTest {
            dependencies {
                implementation(project(":xemantic-typescript-compiler-core"))
            }
        }

    }

}

// The (TSGO.1) gate is selected by environment variables (OracleParityTest, TsgoPinTest); make them
// test inputs, or a run with TSGO_ORACLE=bound after a plain run is UP-TO-DATE and measures nothing.
tasks.withType<Test>().configureEach {
    for (v in listOf(
        "TSGO_ORACLE", "TSGO_ORACLE_LIMIT", "TSGO_ORACLE_SOURCE", "TSGO_ORACLE_REAL_HASH", "TSGO_ORACLE_DIAGS",
        "TSGO_DIAG", "TSGO_DIAG_LIMIT", "TSGO_DIAG_FILTER", "TSGO_SNIPPET",
    )) {
        inputs.property(v, providers.environmentVariable(v).orElse(""))
    }
    // The (TSGO.2) diagnostics differential (DiagParityTest) builds a Program per configuration; the
    // bundled libs alone are ~100 MB of AST. Opt-in larger heap, so a plain run keeps Gradle's default.
    providers.environmentVariable("TSGO_TEST_HEAP").orNull?.let { maxHeapSize = it }
}
