/*
 * SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * xemantic-typescript-compiler - a conformant TypeScript compiler and type
 * checker that runs on JVM, native, and WebAssembly
 * Copyright (C) 2026 Kazimierz Pogoda / Xemantic
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, this file contains Helper Code covered by the
 * xemantic-typescript-compiler Output Exception; additional permissions
 * are granted as described in the file LICENSE-EXCEPTION.
 */

package com.xemantic.typescript.goport

import com.xemantic.typescript.goport.ir.IrPackage
import com.xemantic.typescript.goport.ir.list
import com.xemantic.typescript.goport.ir.str
import com.xemantic.typescript.goport.lower.FileCtx
import com.xemantic.typescript.goport.lower.Item
import com.xemantic.typescript.goport.lower.Override
import com.xemantic.typescript.goport.lower.PackageEmitter
import com.xemantic.typescript.goport.lower.PkgCtx
import com.xemantic.typescript.goport.lower.Program
import com.xemantic.typescript.goport.lower.Literals
import com.xemantic.typescript.goport.lower.ShimIndex
import com.xemantic.typescript.goport.naming.Naming
import com.xemantic.typescript.goport.naming.RenameTable
import com.xemantic.typescript.goport.report.Report
import java.io.File
import kotlin.system.exitProcess

/** The D2 header (docs/tsgo-port-plan.md § 6) every generated file starts with. */
/**
 * A third-party Go package (a dependency of typescript-go, version from its go.mod) the port lowers
 * mechanically like tsgo's own; its original licence travels with it ([license] in -tsgo).
 */
class ThirdParty(val version: String, val copyright: String, val licenseName: String, val license: String)

/** Every third-party package the porter accepts; an IR package outside tsgo and this table is refused. */
val THIRD_PARTY = mapOf(
    // (TSGO.3) tsgo's baseline diff (`baseline.DiffText`), printed by the `.js` emit baseline's noCheck comparison.
    "github.com/peter-evans/patience" to ThirdParty("v0.3.0", "Copyright (c) 2022 Peter Evans", "the MIT License", "LICENSE-patience"),
)

fun header(goSources: List<String>, pkg: IrPackage? = null): String =
    if (pkg == null || pkg.isTsgo) header(goSources) else thirdPartyHeader(goSources, pkg.path, THIRD_PARTY.getValue(pkg.path))

fun thirdPartyHeader(goSources: List<String>, path: String, tp: ThirdParty): String = """
/*
 * GENERATED by xemantic-typescript-compiler-goport — do not edit. Change the porter
 * (xemantic-typescript-compiler-goport) or add an override (…-goport/overrides/).
 *
 * Derived from $path ${tp.version} (https://$path), a dependency of
 * typescript-go at tag typescript/v7.0.2, ${goSources.joinToString(", ")}, and MODIFIED:
 * mechanically translated from Go to Kotlin.
 *
 * Original work ${tp.copyright}, licensed under ${tp.licenseName} — see
 * ${tp.license} in xemantic-typescript-compiler-tsgo.
 *
 * Modifications Copyright (C) 2026 Kazimierz Pogoda / Xemantic.
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * The modified work is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, version 3 of the License. It is distributed WITHOUT ANY WARRANTY; see the
 * GNU Affero General Public License for more details <https://www.gnu.org/licenses/>.
 * As a special exception, additional permissions are granted as described in the file
 * LICENSE-EXCEPTION.
 */
""".trimStart()

fun header(goSources: List<String>): String = """
/*
 * GENERATED by xemantic-typescript-compiler-goport — do not edit. Change the porter
 * (xemantic-typescript-compiler-goport) or add an override (…-goport/overrides/).
 *
 * Derived from typescript-go (https://github.com/microsoft/typescript-go) at tag
 * typescript/v7.0.2 (2bd066d87f5b), ${goSources.joinToString(", ")}, and MODIFIED:
 * mechanically translated from Go to Kotlin.
 *
 * Original work Copyright (c) Microsoft Corporation, licensed under the Apache License,
 * Version 2.0 — see LICENSE and NOTICE.txt in xemantic-typescript-compiler-tsgo.
 *
 * Modifications Copyright (C) 2026 Kazimierz Pogoda / Xemantic.
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * The modified work is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, version 3 of the License. It is distributed WITHOUT ANY WARRANTY; see the
 * GNU Affero General Public License for more details <https://www.gnu.org/licenses/>.
 * As a special exception, additional permissions are granted as described in the file
 * LICENSE-EXCEPTION.
 */
""".trimStart()

/**
 * Warnings that mechanically translated Go legitimately produces in Kotlin (Go allows unused
 * parameters, our `!!` mirrors Go's nil dereference even where Kotlin smart-casts, …). The build
 * stays warning-clean; anything NOT on this list surfaces.
 */
/** `//go:embed` data: chars per string constant and per generated file. */
const val EMBED_CHUNK = 16_000
const val EMBED_FILE = 240_000

val SUPPRESS = listOf(
    "UNUSED_PARAMETER", "UNUSED_VARIABLE", "UNUSED_VALUE", "UNCHECKED_CAST", "USELESS_CAST",
    "UNNECESSARY_NOT_NULL_ASSERTION", "UNREACHABLE_CODE", "NAME_SHADOWING", "REDUNDANT_ELSE_IN_WHEN",
    "SENSELESS_COMPARISON", "UNNECESSARY_SAFE_CALL", "USELESS_IS_CHECK", "UNUSED_EXPRESSION",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER", "ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE", "CAN_BE_VAL",
    "UNUSED_ANONYMOUS_PARAMETER", "REDUNDANT_CALL_OF_CONVERSION_METHOD", "KotlinConstantConditions",
    "unused", "LocalVariableName", "FunctionName", "PropertyName", "ClassName", "ObjectPropertyName",
    "RemoveRedundantQualifierName", "RedundantVisibilityModifier", "UNUSED_LAMBDA_EXPRESSION",
    "IDENTITY_SENSITIVE_OPERATIONS_WITH_VALUE_TYPE", "DEPRECATION", "VARIABLE_INITIALIZER_IS_REDUNDANT",
    "VARIABLE_NEVER_READ", "ASSIGNED_VALUE_IS_NEVER_READ", "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "DIFFERENT_NAMES_FOR_THE_SAME_PARAMETER_IN_SUPERTYPES",
)

class Args(argv: Array<String>) {
    private val m = argv.toList().chunked(2).associate { it[0] to it.getOrElse(1) { "" } }
    val ir = File(m["--ir"] ?: "build/goport/ir")
    val overrides = File(m["--overrides"] ?: "xemantic-typescript-compiler-goport/overrides")
    val renames = File(m["--renames"] ?: "xemantic-typescript-compiler-goport/renames.txt")
    val refuse = File(m["--refuse"] ?: "xemantic-typescript-compiler-goport/refuse.txt")
    val out = File(m["--out"] ?: "xemantic-typescript-compiler-tsgo/src/commonMain/kotlin/gen")
    val report = m["--report"]?.let { File(it) }
    val tsgo = File(m["--tsgo"] ?: "typescript-go-repo")
}

fun loadOverrides(dir: File): Map<String, Override> {
    if (!dir.isDirectory) return emptyMap()
    val out = HashMap<String, Override>()
    for (f in dir.listFiles()!!.filter { it.name.endsWith(".kt") }.sortedBy { it.name }) {
        val lines = f.readLines()
        val trace = lines.firstOrNull { it.startsWith("// go: ") } ?: error("${f.name}: no '// go: <qname> <hash8>' line")
        val (_, _, qname, hash) = trace.split(' ')
        val text = lines.dropWhile { !it.startsWith("// go: ") }.drop(1).joinToString("\n")
        out[qname] = Override(qname, hash, text, f.name)
    }
    return out
}

fun camelFile(goFile: String): String =
    goFile.removeSuffix(".go").split('_').joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }

fun main(argv: Array<String>) {
    val args = Args(argv)
    val index = File(args.ir, "index.json")
    require(index.isFile) { "no IR at ${args.ir} — run goport-extract first (docs/goport-ir.md § 1)" }
    val t0 = System.currentTimeMillis()
    val files = args.ir.listFiles()!!.filter { it.name != "index.json" && it.name.endsWith(".json") }.sortedBy { it.name }
    val packages = files.map { IrPackage.load(it) }
    for (p in packages) require(p.isTsgo || p.path in THIRD_PARTY) {
        "IR package ${p.path} is neither typescript-go's nor a known third-party package (THIRD_PARTY in Main.kt: version, copyright, licence)"
    }
    val tsgoMain = args.out.parentFile
    val shims = ShimIndex.scan(File(tsgoMain, "go"), File(tsgoMain, "runtime"))
    val renames = RenameTable.load(args.renames)
    val overrides = loadOverrides(args.overrides)
    val prog = Program(packages, shims, renames)
    prog.computeInlineFuncs(overrides.keys)
    prog.computeWindowFields()
    prog.computeImmutableStructs()
    for ((k, why) in prog.immutableRefusals) println("goport: immutable struct refused: $k — $why")
    prog.computeWindowFuncs(overrides.keys)
    val pinned = RenameTable.load(args.refuse).let { t -> t.entries() }
    val report = Report()
    for (m0 in prog.shadowedAliasMethods) report.collision("$m0 — add a rename to renames.txt")

    if (args.out.exists()) args.out.deleteRecursively()
    args.out.mkdirs()

    var written = 0
    for (p in packages) {
        val pc = PkgCtx(prog, p)
        val em = PackageEmitter(pc, overrides, report, pinned)
        em.checkPackageCollisions()
        val dir = File(args.out, p.shortPath)
        dir.mkdirs()
        for (f in p.files) {
            val goFile = f.str("name")!!
            val base = camelFile(goFile)
            // Lower once with a throwaway import context to learn the item sizes, then render
            // each chunk with its own imports.
            val chunks = ArrayList<List<Item>>()
            val fcAll = FileCtx(pc)
            val items = em.lowerFile(f, fcAll)
            var cur = ArrayList<Item>()
            var lines = 0
            var vars = 0
            for (it in items) {
                if (cur.isNotEmpty() && (lines + it.goLines > CHUNK_LINES || (it.isVar && vars >= CHUNK_VARS))) {
                    chunks += cur
                    cur = ArrayList()
                    lines = 0
                    vars = 0
                }
                cur += it
                lines += it.goLines
                if (it.isVar) vars++
            }
            if (cur.isNotEmpty()) chunks += cur
            chunks.forEachIndexed { ci, chunk ->
                val name = if (chunks.size == 1) "$base.kt" else "$base${ci + 1}.kt"
                File(dir, name).writeText(render(pc, fcAll, chunk, "${p.sourceDir}/$goFile"))
                written++
            }
        }
        prog.anonStructs[p.path]?.let { reg ->
            val body = reg.values.joinToString("\n")
            File(dir, "AnonStructs.kt").writeText(render(pc, FileCtx(pc), listOf(Item(0, body, false)), "anonymous struct types of ${p.sourceDir}"))
            written++
        }
        val inits = p.files.flatMap { f -> f.list("decls").filter { it.str("k") == "FuncDecl" && it.str("name") == "init" } }
        if (inits.isNotEmpty()) {
            val fc = FileCtx(pc)
            val body = buildString {
                appendLine("/** Go's package initialization (`func init()`), run explicitly by whoever uses the package. */")
                appendLine("fun goInitPackage() {")
                inits.forEachIndexed { i, _ -> appendLine("    init${if (i == 0) "" else "_$i"}()") }
                appendLine("}")
            }
            File(dir, "PackageInit.kt").writeText(render(pc, fc, listOf(Item(0, body, false)), p.sourceDir))
        }
    }
    // `//go:embed` contents (Program.embeds): byte-string chunks of <= EMBED_CHUNK chars (a JVM constant
    // holds 65,535 UTF-8 bytes; an escaped high byte takes 2), files of <= EMBED_FILE chars.
    for ((path, list) in prog.embeds) {
        val p = packages.first { it.path == path }
        val pc = PkgCtx(prog, p)
        val dir = File(args.out, p.shortPath)
        val pkgDir = File(args.tsgo, "internal/${p.shortPath}")
        val index = StringBuilder()
        val files = ArrayList<StringBuilder>()
        var cur = StringBuilder()
        var size = 0
        for ((fnName, pat) in list) {
            val bytes = File(pkgDir, pat).readBytes()
            val parts = ArrayList<String>()
            var off = 0
            while (off < bytes.size || parts.isEmpty()) {
                val end = minOf(bytes.size, off + EMBED_CHUNK)
                val cname = "${fnName}_${parts.size}"
                if (size > EMBED_FILE) { files += cur; cur = StringBuilder(); size = 0 }
                cur.append("internal const val $cname: String = ${Literals.byteString(bytes.copyOfRange(off, end))}\n")
                size += end - off
                parts += cname
                off = end
            }
            index.append("/** The bytes of `$pat` (`//go:embed`). */\n")
            index.append("internal fun $fnName(): String = StringBuilder(${bytes.size})${parts.joinToString("") { ".append($it)" }}.toString()\n\n")
        }
        if (cur.isNotEmpty()) files += cur
        files.forEachIndexed { i, b ->
            File(dir, "EmbedData${i + 1}.kt").writeText(render(pc, FileCtx(pc), listOf(Item(0, b.toString(), false)), "go:embed data of internal/${p.shortPath}"))
            written++
        }
        File(dir, "EmbedIndex.kt").writeText(render(pc, FileCtx(pc), listOf(Item(0, index.toString(), false)), "go:embed index of internal/${p.shortPath}"))
        written++
    }
    // Synthetic interfaces for anonymous Go interfaces.
    if (prog.synth.needNullable) {
        // A nullable view of a non-null reference: Kotlin does not smart-cast a call result, so a call on it
        // resolves to the nil-safe EXTENSION rather than the member of the same name.
        prog.synth.bodies["goNullable"] = "/** [x] typed as nullable (selects a nil-safe extension over a member). */\nfun <T : Any> goNullable(x: T): T? = x\n"
    }
    if (prog.synth.bodies.isNotEmpty()) {
        val dir = File(args.out, "synth")
        dir.mkdirs()
        val text = buildString {
            append(header(listOf("anonymous interfaces of several packages")))
            appendLine("@file:Suppress(${SUPPRESS.joinToString(", ") { "\"$it\"" }})")
            appendLine()
            appendLine("package ${Naming.SYNTH}")
            appendLine()
            appendLine("import ${Naming.RUNTIME}.*")
            appendLine()
            for ((_, b) in prog.synth.bodies) {
                append(b)
                appendLine()
            }
        }
        File(dir, "Ifaces.kt").writeText(text)
        written++
    }

    val unusedOverrides = overrides.values.filter { !it.used }
    val text = report.render() + buildString {
        if (unusedOverrides.isNotEmpty()) {
            appendLine()
            appendLine("ORPHAN OVERRIDES (${unusedOverrides.size}):")
            unusedOverrides.forEach { appendLine("  ${it.file}: no declaration ${it.qname}") }
        }
        appendLine()
        appendLine("wrote $written files in ${System.currentTimeMillis() - t0} ms")
    }
    println(text)
    val reportDir = File(args.ir.parentFile, "port")
    reportDir.mkdirs()
    File(reportDir, "report.txt").writeText(text)
    File(reportDir, "refused.tsv").writeText(report.refusedDecls.joinToString("\n") + "\n")
    File(reportDir, "lowered.txt").writeText(report.loweredDecls.joinToString("\n") + "\n")
    if (report.stale.isNotEmpty() || unusedOverrides.isNotEmpty() || report.collisions.isNotEmpty()) exitProcess(1)
}

const val CHUNK_LINES = 3000
const val CHUNK_VARS = 150

fun render(pc: PkgCtx, fc: FileCtx, items: List<Item>, source: String): String = buildString {
    append(header(listOf(source), pc.pkg))
    appendLine("@file:Suppress(${SUPPRESS.joinToString(", ") { "\"$it\"" }})")
    appendLine()
    appendLine("package ${pc.kotlinPackage}")
    appendLine()
    appendLine("import ${Naming.RUNTIME}.*")
    for ((_, fqn) in fc.imports) appendLine("import $fqn")
    for (fqn in fc.funImports) if (fqn !in fc.imports.values) appendLine("import $fqn")
    appendLine()
    for (it in items) {
        append(it.text)
        appendLine()
    }
}
