/*
 * SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * xemantic-typescript-compiler - a conformant TypeScript compiler and type
 * checker that runs on JVM, native, and WebAssembly
 * Copyright (C) 2026 Kazimierz Pogoda / Xemantic
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, this file contains Helper Code covered by the
 * xemantic-typescript-compiler Output Exception; additional permissions
 * are granted as described in the file LICENSE-EXCEPTION.
 */

package com.xemantic.typescript.goport

import com.xemantic.typescript.goport.ir.IrPackage
import com.xemantic.typescript.goport.ir.list
import com.xemantic.typescript.goport.ir.str
import com.xemantic.typescript.goport.lower.FileCtx
import com.xemantic.typescript.goport.lower.Item
import com.xemantic.typescript.goport.lower.Override
import com.xemantic.typescript.goport.lower.PackageEmitter
import com.xemantic.typescript.goport.lower.PkgCtx
import com.xemantic.typescript.goport.lower.Program
import com.xemantic.typescript.goport.lower.ShimIndex
import com.xemantic.typescript.goport.naming.Naming
import com.xemantic.typescript.goport.naming.RenameTable
import com.xemantic.typescript.goport.report.Report
import java.io.File
import kotlin.system.exitProcess

/** The D2 header (docs/tsgo-port-plan.md § 6) every generated file starts with. */
fun header(goSources: List<String>): String = """
/*
 * GENERATED by xemantic-typescript-compiler-goport — do not edit. Change the porter
 * (xemantic-typescript-compiler-goport) or add an override (…-goport/overrides/).
 *
 * Derived from typescript-go (https://github.com/microsoft/typescript-go) at tag
 * typescript/v7.0.2 (2bd066d87f5b), ${goSources.joinToString(", ")}, and MODIFIED:
 * mechanically translated from Go to Kotlin.
 *
 * Original work Copyright (c) Microsoft Corporation, licensed under the Apache License,
 * Version 2.0 — see LICENSE and NOTICE.txt in xemantic-typescript-compiler-tsgo.
 *
 * Modifications Copyright (C) 2026 Kazimierz Pogoda / Xemantic.
 * SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
 *
 * The modified work is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, version 3 of the License. It is distributed WITHOUT ANY WARRANTY; see the
 * GNU Affero General Public License for more details <https://www.gnu.org/licenses/>.
 * As a special exception, additional permissions are granted as described in the file
 * LICENSE-EXCEPTION.
 */
""".trimStart()

/**
 * Warnings that mechanically translated Go legitimately produces in Kotlin (Go allows unused
 * parameters, our `!!` mirrors Go's nil dereference even where Kotlin smart-casts, …). The build
 * stays warning-clean; anything NOT on this list surfaces.
 */
val SUPPRESS = listOf(
    "UNUSED_PARAMETER", "UNUSED_VARIABLE", "UNUSED_VALUE", "UNCHECKED_CAST", "USELESS_CAST",
    "UNNECESSARY_NOT_NULL_ASSERTION", "UNREACHABLE_CODE", "NAME_SHADOWING", "REDUNDANT_ELSE_IN_WHEN",
    "SENSELESS_COMPARISON", "UNNECESSARY_SAFE_CALL", "USELESS_IS_CHECK", "UNUSED_EXPRESSION",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER", "ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE", "CAN_BE_VAL",
    "UNUSED_ANONYMOUS_PARAMETER", "REDUNDANT_CALL_OF_CONVERSION_METHOD", "KotlinConstantConditions",
    "unused", "LocalVariableName", "FunctionName", "PropertyName", "ClassName", "ObjectPropertyName",
    "RemoveRedundantQualifierName", "RedundantVisibilityModifier", "UNUSED_LAMBDA_EXPRESSION",
    "IDENTITY_SENSITIVE_OPERATIONS_WITH_VALUE_TYPE", "DEPRECATION", "VARIABLE_INITIALIZER_IS_REDUNDANT",
    "VARIABLE_NEVER_READ", "ASSIGNED_VALUE_IS_NEVER_READ", "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "DIFFERENT_NAMES_FOR_THE_SAME_PARAMETER_IN_SUPERTYPES",
)

class Args(argv: Array<String>) {
    private val m = argv.toList().chunked(2).associate { it[0] to it.getOrElse(1) { "" } }
    val ir = File(m["--ir"] ?: "build/goport/ir")
    val overrides = File(m["--overrides"] ?: "xemantic-typescript-compiler-goport/overrides")
    val renames = File(m["--renames"] ?: "xemantic-typescript-compiler-goport/renames.txt")
    val refuse = File(m["--refuse"] ?: "xemantic-typescript-compiler-goport/refuse.txt")
    val out = File(m["--out"] ?: "xemantic-typescript-compiler-tsgo/src/commonMain/kotlin/gen")
    val report = m["--report"]?.let { File(it) }
}

fun loadOverrides(dir: File): Map<String, Override> {
    if (!dir.isDirectory) return emptyMap()
    val out = HashMap<String, Override>()
    for (f in dir.listFiles()!!.filter { it.name.endsWith(".kt") }.sortedBy { it.name }) {
        val lines = f.readLines()
        val trace = lines.firstOrNull { it.startsWith("// go: ") } ?: error("${f.name}: no '// go: <qname> <hash8>' line")
        val (_, _, qname, hash) = trace.split(' ')
        val text = lines.dropWhile { !it.startsWith("// go: ") }.drop(1).joinToString("\n")
        out[qname] = Override(qname, hash, text, f.name)
    }
    return out
}

fun camelFile(goFile: String): String =
    goFile.removeSuffix(".go").split('_').joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }

fun main(argv: Array<String>) {
    val args = Args(argv)
    val index = File(args.ir, "index.json")
    require(index.isFile) { "no IR at ${args.ir} — run goport-extract first (docs/goport-ir.md § 1)" }
    val t0 = System.currentTimeMillis()
    val files = args.ir.listFiles()!!.filter { it.name.startsWith("internal_") && it.name.endsWith(".json") }.sortedBy { it.name }
    val packages = files.map { IrPackage.load(it) }
    val tsgoMain = args.out.parentFile
    val shims = ShimIndex.scan(File(tsgoMain, "go"), File(tsgoMain, "runtime"))
    val renames = RenameTable.load(args.renames)
    val overrides = loadOverrides(args.overrides)
    val prog = Program(packages, shims, renames)
    val pinned = RenameTable.load(args.refuse).let { t -> t.entries() }
    val report = Report()

    if (args.out.exists()) args.out.deleteRecursively()
    args.out.mkdirs()

    var written = 0
    for (p in packages) {
        val pc = PkgCtx(prog, p)
        val em = PackageEmitter(pc, overrides, report, pinned)
        em.checkPackageCollisions()
        val dir = File(args.out, p.shortPath)
        dir.mkdirs()
        for (f in p.files) {
            val goFile = f.str("name")!!
            val base = camelFile(goFile)
            // Lower once with a throwaway import context to learn the item sizes, then render
            // each chunk with its own imports.
            val chunks = ArrayList<List<Item>>()
            val fcAll = FileCtx(pc)
            val items = em.lowerFile(f, fcAll)
            var cur = ArrayList<Item>()
            var lines = 0
            var vars = 0
            for (it in items) {
                if (cur.isNotEmpty() && (lines + it.goLines > CHUNK_LINES || (it.isVar && vars >= CHUNK_VARS))) {
                    chunks += cur
                    cur = ArrayList()
                    lines = 0
                    vars = 0
                }
                cur += it
                lines += it.goLines
                if (it.isVar) vars++
            }
            if (cur.isNotEmpty()) chunks += cur
            chunks.forEachIndexed { ci, chunk ->
                val name = if (chunks.size == 1) "$base.kt" else "$base${ci + 1}.kt"
                File(dir, name).writeText(render(pc, fcAll, chunk, "internal/${p.shortPath}/$goFile"))
                written++
            }
        }
        prog.anonStructs[p.path]?.let { reg ->
            val body = reg.values.joinToString("\n")
            File(dir, "AnonStructs.kt").writeText(render(pc, FileCtx(pc), listOf(Item(0, body, false)), "anonymous struct types of internal/${p.shortPath}"))
            written++
        }
        val inits = p.files.flatMap { f -> f.list("decls").filter { it.str("k") == "FuncDecl" && it.str("name") == "init" } }
        if (inits.isNotEmpty()) {
            val fc = FileCtx(pc)
            val body = buildString {
                appendLine("/** Go's package initialization (`func init()`), run explicitly by whoever uses the package. */")
                appendLine("fun goInitPackage() {")
                inits.forEachIndexed { i, _ -> appendLine("    init${if (i == 0) "" else "_$i"}()") }
                appendLine("}")
            }
            File(dir, "PackageInit.kt").writeText(render(pc, fc, listOf(Item(0, body, false)), "internal/${p.shortPath}"))
        }
    }
    // Synthetic interfaces for anonymous Go interfaces.
    if (prog.synth.bodies.isNotEmpty()) {
        val dir = File(args.out, "synth")
        dir.mkdirs()
        val text = buildString {
            append(header(listOf("anonymous interfaces of several packages")))
            appendLine("@file:Suppress(${SUPPRESS.joinToString(", ") { "\"$it\"" }})")
            appendLine()
            appendLine("package ${Naming.SYNTH}")
            appendLine()
            appendLine("import ${Naming.RUNTIME}.*")
            appendLine()
            for ((_, b) in prog.synth.bodies) {
                append(b)
                appendLine()
            }
        }
        File(dir, "Ifaces.kt").writeText(text)
        written++
    }

    val unusedOverrides = overrides.values.filter { !it.used }
    val text = report.render() + buildString {
        if (unusedOverrides.isNotEmpty()) {
            appendLine()
            appendLine("ORPHAN OVERRIDES (${unusedOverrides.size}):")
            unusedOverrides.forEach { appendLine("  ${it.file}: no declaration ${it.qname}") }
        }
        appendLine()
        appendLine("wrote $written files in ${System.currentTimeMillis() - t0} ms")
    }
    println(text)
    val reportDir = File(args.ir.parentFile, "port")
    reportDir.mkdirs()
    File(reportDir, "report.txt").writeText(text)
    File(reportDir, "refused.tsv").writeText(report.refusedDecls.joinToString("\n") + "\n")
    File(reportDir, "lowered.txt").writeText(report.loweredDecls.joinToString("\n") + "\n")
    if (report.stale.isNotEmpty() || unusedOverrides.isNotEmpty() || report.collisions.isNotEmpty()) exitProcess(1)
}

const val CHUNK_LINES = 3000
const val CHUNK_VARS = 150

fun render(pc: PkgCtx, fc: FileCtx, items: List<Item>, source: String): String = buildString {
    append(header(listOf(source)))
    appendLine("@file:Suppress(${SUPPRESS.joinToString(", ") { "\"$it\"" }})")
    appendLine()
    appendLine("package ${pc.kotlinPackage}")
    appendLine()
    appendLine("import ${Naming.RUNTIME}.*")
    for ((_, fqn) in fc.imports) appendLine("import $fqn")
    for (fqn in fc.funImports) if (fqn !in fc.imports.values) appendLine("import $fqn")
    appendLine()
    for (it in items) {
        append(it.text)
        appendLine()
    }
}
