#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
#
# xemantic-typescript-compiler - a conformant TypeScript compiler and type
# checker that runs on JVM, native, and WebAssembly
# Copyright (C) 2026 Kazimierz Pogoda / Xemantic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# As a special exception, this file contains Helper Code covered by the
# xemantic-typescript-compiler Output Exception; additional permissions
# are granted as described in the file LICENSE-EXCEPTION.
#

# Performance benchmark: compile the TypeScript compiler with THIS compiler.
#
# Compiles subprojects of TypeScript's own source tree — taken from the
# `typescript-repo` clone, which is PINNED to the exact commit the test corpus
# tracks (`typeScriptCommit` in build.gradle.kts) — using the xtsc
# whole-project CLI (`MainKt`) on the JVM.
#
# Available --project profiles (each is the named src/ dir plus the transitive
# closure of its tsconfig `references`, compiled as ONE program — we do not
# model project references, so the reference graph is flattened):
#
#   compiler              src/compiler                          (~77 files, default)
#   tsc                   + src/tsc                             (~79 files)
#   jsTyping              + src/jsTyping                        (~83 files)
#   deprecatedCompat      + src/deprecatedCompat                (~80 files)
#   typingsInstallerCore  + jsTyping + typingsInstallerCore     (~87 files)
#   services              + jsTyping + services                 (~251 files)
#   server                + jsTyping + tic + services + dc + server    (~273 files)
#   harness               + all of the above + harness          (~311 files)
#   all                   run every profile above in sequence
#
# Each run reports and logs:
#   - self-reported compile time (ProjectCompiler.build, excludes JVM startup)
#   - wall-clock time of the java process (cold-CLI experience, includes JIT)
#   - peak RSS (when GNU time is available)
#   - diagnostic counts, total + by-code breakdown (compliance drift signal:
#     real tsc reports 0 errors on its own source, so every error we emit is
#     a false positive or a modeling gap — the count should only go down)
#
# Results are appended per project — bench/self-compile-tsc.tsv for the
# `compiler` profile (historical name), bench/self-compile-<project>.tsv for
# the rest (one row per invocation, keyed by the xtsc git revision), so
# performance and compliance can be compared across compiler changes:
#
#   scripts/bench-compile-tsc.sh --label "before checker change"
#   ... hack hack hack ...
#   scripts/bench-compile-tsc.sh --label "after checker change"
#
# NOTE: this measures the cold single-shot CLI (fresh JVM per run — JIT warm-up
# is part of the measurement, matching what a CLI user experiences). For warm
# in-process rebuild benchmarking use src/commonTest/kotlin/BenchMain.kt.
#
# Usage: scripts/bench-compile-tsc.sh [options]
#   --project NAME   which tsc subproject to compile (see profiles above;
#                    comma-separated list or "all" accepted; default compiler)
#   --iterations N   measured runs, median reported (default 1; ~4-5 min each
#                    for the compiler profile as of 2026-07)
#   --warmup N       unmeasured warm-up runs before measuring (default 0)
#   --heap SIZE      JVM -Xmx for the compiler process (default 4g)
#   --no-emit        type-check only (skip JS emit)
#   --fresh          re-extract + regenerate the benchmark project even if a
#                    cached copy exists
#   --label TEXT     free-text note stored in the results log
#   --no-log         do not append to the bench/ results TSV
#   --help           show this help
#
# Each benchmark project is materialized under build/bench/tsc-<name>-<commit8>/
# (`tsc-project-<commit8>` for the compiler profile — historical name; cheap to
# rebuild — safe to lose on `rm -rf build`):
#   - `git archive` of the profile's src/ dirs from typescript-repo's object
#     store (works with the sparse checkout; the object DB has the full tree)
#   - src/compiler/diagnosticInformationMap.generated.ts generated by an inline
#     Python port of TypeScript's scripts/processDiagnosticMessages.mjs (it is
#     a build artifact, not checked in — tsc's source does not parse without it)
#   - a merged tsconfig.json (their tsconfig-base minus composite /
#     emitDeclarationOnly / declaration / sourceMap, plus outDir=dist).
#     `types` is emptied for every profile: no node_modules/@types is
#     materialized, so node/mocha/chai-typed code (server, harness) reports
#     env-legit diagnostics until M1.3 lands @types resolution.
#
# Prerequisite: typescript-repo cloned (the script runs
# `./gradlew cloneTypeScriptRepo` automatically when it is missing).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PROJECT_ARG=compiler
ITERATIONS=1
WARMUP=0
HEAP=4g
NO_EMIT=0
FRESH=0
LABEL=""
DO_LOG=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project)    PROJECT_ARG="$2"; shift 2 ;;
        --iterations) ITERATIONS="$2"; shift 2 ;;
        --warmup)     WARMUP="$2"; shift 2 ;;
        --heap)       HEAP="$2"; shift 2 ;;
        --no-emit)    NO_EMIT=1; shift ;;
        --fresh)      FRESH=1; shift ;;
        --label)      LABEL="$2"; shift 2 ;;
        --no-log)     DO_LOG=0; shift ;;
        --help|-h)    sed -n '/^# Performance benchmark/,/^set -euo/p' "$0" | sed '$d;s/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $1 (see --help)" >&2; exit 2 ;;
    esac
done

command -v java >/dev/null || { echo "error: java not found on PATH" >&2; exit 1; }
command -v python3 >/dev/null || { echo "error: python3 not found on PATH" >&2; exit 1; }

BENCH_BUILD_DIR="$REPO_ROOT/build/bench"
RESULTS_DIR="$REPO_ROOT/bench"
mkdir -p "$BENCH_BUILD_DIR"

# ---------------------------------------------------------------------------
# Project profiles: src/ dirs per profile = the named dir plus the transitive
# closure of its tsconfig `references` (verified against the pinned commit's
# src/*/tsconfig.json). Compiled as one flat program.
# ---------------------------------------------------------------------------

ALL_PROJECTS=(compiler tsc jsTyping deprecatedCompat typingsInstallerCore services server harness)

project_dirs() {
    case "$1" in
        compiler)             echo "compiler" ;;
        tsc)                  echo "compiler tsc" ;;
        jsTyping)             echo "compiler jsTyping" ;;
        deprecatedCompat)     echo "compiler deprecatedCompat" ;;
        typingsInstallerCore) echo "compiler jsTyping typingsInstallerCore" ;;
        services)             echo "compiler jsTyping services" ;;
        server)               echo "compiler jsTyping typingsInstallerCore services deprecatedCompat server" ;;
        harness)              echo "compiler jsTyping typingsInstallerCore services deprecatedCompat server harness" ;;
        *) return 1 ;;
    esac
}

results_tsv_for() { # historical name for the compiler profile, per-project otherwise
    case "$1" in
        compiler) echo "$RESULTS_DIR/self-compile-tsc.tsv" ;;
        # The src/tsc CLI profile must NOT collide with the compiler profile's
        # historical file name above.
        tsc)      echo "$RESULTS_DIR/self-compile-tsc-cli.tsv" ;;
        *)        echo "$RESULTS_DIR/self-compile-$1.tsv" ;;
    esac
}

proj_dir_for() {
    if [[ "$1" == compiler ]]; then echo "$BENCH_BUILD_DIR/tsc-project-$TS_COMMIT8"
    else echo "$BENCH_BUILD_DIR/tsc-$1-$TS_COMMIT8"; fi
}

if [[ "$PROJECT_ARG" == all ]]; then
    PROJECTS=("${ALL_PROJECTS[@]}")
else
    IFS=',' read -r -a PROJECTS <<<"$PROJECT_ARG"
fi
for P in "${PROJECTS[@]}"; do
    project_dirs "$P" >/dev/null || {
        echo "error: unknown project '$P' (known: ${ALL_PROJECTS[*]}, or 'all')" >&2; exit 2; }
done

# ---------------------------------------------------------------------------
# 1. The TypeScript sources — pinned version via typescript-repo.
# ---------------------------------------------------------------------------

if [[ ! -e "$REPO_ROOT/typescript-repo/.git" ]]; then
    echo "typescript-repo missing — cloning via ./gradlew cloneTypeScriptRepo ..."
    "$REPO_ROOT/gradlew" -q cloneTypeScriptRepo
fi

TS_COMMIT="$(git -C "$REPO_ROOT/typescript-repo" rev-parse HEAD)"
TS_COMMIT8="${TS_COMMIT:0:8}"

materialize_project() { # $1 = project name; sets PROJ_DIR
    local project="$1"
    PROJ_DIR="$(proj_dir_for "$project")"

    if [[ $FRESH -eq 1 ]]; then
        rm -rf "$PROJ_DIR"
    fi
    [[ -f "$PROJ_DIR/tsconfig.json" ]] && return 0

    local dirs paths=()
    dirs="$(project_dirs "$project")"
    for d in $dirs; do paths+=("src/$d"); done

    echo "materializing benchmark project at $PROJ_DIR (tsc @ $TS_COMMIT8: ${dirs// /, }) ..."
    rm -rf "$PROJ_DIR"
    mkdir -p "$PROJ_DIR"

    # Extract the profile's dirs from the object store (sparse checkout has no
    # working-tree copy, but `git archive HEAD` reads the full tree).
    git -C "$REPO_ROOT/typescript-repo" archive HEAD "${paths[@]}" | tar -x -C "$PROJ_DIR"

    # Generate diagnosticInformationMap.generated.ts — a faithful port of
    # typescript-repo/scripts/processDiagnosticMessages.mjs (buildInfoFileOutput,
    # convertPropertyName, createKey), which tsc's own build runs with Node.
    # Every profile includes src/compiler, so this always applies.
    python3 - "$PROJ_DIR/src/compiler/diagnosticMessages.json" \
              "$PROJ_DIR/src/compiler/diagnosticInformationMap.generated.ts" <<'PYEOF'
import json, re, sys

src, out = sys.argv[1], sys.argv[2]
with open(src, encoding="utf-8") as f:
    table = json.load(f)  # dict preserves JSON insertion order

def convert_property_name(orig):
    result = "".join(
        "_Asterisk" if ch == "*"
        else "_Slash" if ch == "/"
        else "_Colon" if ch == ":"
        else (ch if re.match(r"[A-Za-z0-9_]", ch) else "_")  # JS \w is ASCII
        for ch in orig
    )
    result = re.sub(r"_+", "_", result)         # collapse multi-underscores
    result = re.sub(r"^_(\D)", r"\1", result)   # strip leading _ unless digit follows
    result = re.sub(r"_$", "", result)          # strip trailing _
    return result

def js(v):  # render a JSON truthy marker the way a JS template literal would
    return "true" if v is True else json.dumps(v, ensure_ascii=False)

lines = [
    "// <auto-generated />",
    "// generated from './diagnosticMessages.json' by scripts/bench-compile-tsc.sh",
    "// (inline port of typescript-repo/scripts/processDiagnosticMessages.mjs)",
    "",
    'import { DiagnosticCategory, DiagnosticMessage } from "./types.js";',
    "",
    "function diag(code: number, category: DiagnosticCategory, key: string, message: string, reportsUnnecessary?: {}, elidedInCompatabilityPyramid?: boolean, reportsDeprecated?: {}): DiagnosticMessage {",
    "    return { code, category, key, message, reportsUnnecessary, elidedInCompatabilityPyramid, reportsDeprecated };",
    "}",
    "",
    "/** @internal */",
    "export const Diagnostics = {",
]
for name, d in table.items():
    prop = convert_property_name(name)
    key = prop[:100] + "_" + str(d["code"])
    arg_ru = f", /*reportsUnnecessary*/ {js(d['reportsUnnecessary'])}" if d.get("reportsUnnecessary") else ""
    arg_el = (
        ("" if d.get("reportsUnnecessary") else ", /*reportsUnnecessary*/ undefined")
        + f", /*elidedInCompatabilityPyramid*/ {js(d['elidedInCompatabilityPyramid'])}"
    ) if d.get("elidedInCompatabilityPyramid") else ""
    arg_rd = (
        ("" if arg_el else ", /*reportsUnnecessary*/ undefined, /*elidedInCompatabilityPyramid*/ undefined")
        + f", /*reportsDeprecated*/ {js(d['reportsDeprecated'])}"
    ) if d.get("reportsDeprecated") else ""
    lines.append(
        f'    {prop}: diag({d["code"]}, DiagnosticCategory.{d["category"]}, "{key}",'
        f' {json.dumps(name, ensure_ascii=False)}{arg_ru}{arg_el}{arg_rd}) as DiagnosticMessage,'
    )
lines.append("};")
lines.append("")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"  generated diagnosticInformationMap.generated.ts ({len(table)} diagnostics)")
PYEOF

    # Merged tsconfig: typescript-repo/src/tsconfig-base.json + the subproject
    # tsconfig.json, minus the project-reference/declaration-only machinery
    # (composite, emitDeclarationOnly, declaration*, sourceMap,
    # isolatedDeclarations) so a plain JS emit is exercised; types [] because
    # no node_modules/@types is materialized (see header note).
    cat > "$PROJ_DIR/tsconfig.json" <<'JSONEOF'
{
    "compilerOptions": {
        "rootDir": "src",
        "outDir": "dist",

        "pretty": true,
        "lib": ["es2020"],
        "target": "es2020",
        "module": "NodeNext",
        "moduleResolution": "NodeNext",

        "strict": true,
        "strictBindCallApply": false,
        "useUnknownInCatchVariables": false,
        "noImplicitOverride": true,

        "skipLibCheck": true,

        "alwaysStrict": true,
        "preserveConstEnums": true,
        "newLine": "lf",

        "types": []
    },
    "include": ["src/**/*"]
}
JSONEOF
}

# ---------------------------------------------------------------------------
# 2. Build the compiler and resolve its runtime classpath.
#    A Gradle *init* script keeps build.gradle.kts untouched.
# ---------------------------------------------------------------------------

INIT_SCRIPT="$BENCH_BUILD_DIR/print-classpath.init.gradle.kts"
cat > "$INIT_SCRIPT" <<'KTSEOF'
// Generated by scripts/bench-compile-tsc.sh — do not edit.
allprojects {
    tasks.register("xtscPrintJvmRuntimeClasspath") {
        doLast {
            val cp = configurations.getByName("jvmRuntimeClasspath")
                .resolve().joinToString(":") { it.absolutePath }
            println("XTSC_CLASSPATH=$cp")
        }
    }
}
KTSEOF

echo "building compiler (compileKotlinJvm) ..."
GRADLE_OUT=$("$REPO_ROOT/gradlew" -q --console=plain -I "$INIT_SCRIPT" \
    compileKotlinJvm xtscPrintJvmRuntimeClasspath)
CLASSPATH="$(grep '^XTSC_CLASSPATH=' <<<"$GRADLE_OUT" | head -1 | cut -d= -f2-)"
[[ -n "$CLASSPATH" ]] || { echo "error: could not resolve jvmRuntimeClasspath" >&2; exit 1; }
CLASSPATH="$REPO_ROOT/build/classes/kotlin/jvm/main:$CLASSPATH"

XTSC_REV="$(git -C "$REPO_ROOT" rev-parse --short=12 HEAD)"
if ! git -C "$REPO_ROOT" diff --quiet || ! git -C "$REPO_ROOT" diff --cached --quiet; then
    XTSC_REV="$XTSC_REV+dirty"
fi

# GNU time gives peak RSS; fall back gracefully when unavailable.
TIME_BIN=""
if /usr/bin/time -v true >/dev/null 2>&1; then TIME_BIN=/usr/bin/time; fi

# ---------------------------------------------------------------------------
# 3. Run.
# ---------------------------------------------------------------------------

RUN_STAMP="$(date -u +%Y%m%dT%H%M%SZ)"

NOEMIT_ARGS=()
[[ $NO_EMIT -eq 1 ]] && NOEMIT_ARGS=(--noEmit)

run_once() { # $1 = log file; uses PROJ_DIR; sets WALL_MS, RSS_KB
    local log="$1" start end
    start=$(date +%s%N)
    local cmd=(java "-Xmx$HEAP" -cp "$CLASSPATH" \
        com.xemantic.typescript.compiler.MainKt "${NOEMIT_ARGS[@]}" "$PROJ_DIR")
    if [[ -n "$TIME_BIN" ]]; then
        "$TIME_BIN" -v -o "$log.time" "${cmd[@]}" >"$log" 2>&1 || {
            echo "error: compiler run failed — tail of $log:" >&2
            tail -20 "$log" >&2; exit 1; }
        RSS_KB=$(grep -oP 'Maximum resident set size \(kbytes\): \K[0-9]+' "$log.time" || echo 0)
    else
        "${cmd[@]}" >"$log" 2>&1 || {
            echo "error: compiler run failed — tail of $log:" >&2
            tail -20 "$log" >&2; exit 1; }
        RSS_KB=0
    fi
    end=$(date +%s%N)
    WALL_MS=$(( (end - start) / 1000000 ))
}

median() {
    printf '%s\n' "$@" | sort -n | awk \
        '{a[NR]=$1} END { if (NR%2) print a[(NR+1)/2]; else print int((a[NR/2]+a[NR/2+1])/2) }'
}

SUMMARY_ROWS=()

bench_project() { # $1 = project name
    local project="$1"
    materialize_project "$project"

    local ts_files ts_loc
    ts_files=$(find "$PROJ_DIR/src" -name '*.ts' | wc -l)
    ts_loc=$(find "$PROJ_DIR/src" -name '*.ts' -print0 | xargs -0 cat | wc -l)
    echo
    echo "=== project '$project' — $ts_files .ts files, $ts_loc LOC (tsc @ $TS_COMMIT8) ==="

    local log_dir="$BENCH_BUILD_DIR/logs/$RUN_STAMP/$project"
    mkdir -p "$log_dir"

    local w i LOG
    for ((w=1; w<=WARMUP; w++)); do
        echo "warmup $w/$WARMUP ..."
        run_once "$log_dir/warmup$w.log"
        echo "  wall ${WALL_MS} ms"
    done

    local SELF_TIMES=() WALL_TIMES=() RSS_MAX_KB=0 SELF_MS
    for ((i=1; i<=ITERATIONS; i++)); do
        echo "run $i/$ITERATIONS ..."
        LOG="$log_dir/run$i.log"
        run_once "$LOG"
        SELF_MS=$(grep -oP '^time:\s+\K[0-9]+' "$LOG" || echo 0)
        SELF_TIMES+=("$SELF_MS"); WALL_TIMES+=("$WALL_MS")
        (( RSS_KB > RSS_MAX_KB )) && RSS_MAX_KB=$RSS_KB
        echo "  self ${SELF_MS} ms, wall ${WALL_MS} ms$( ((RSS_KB>0)) && echo ", rss $((RSS_KB/1024)) MB" )"
    done

    # Parse compliance stats from the last run.
    local ERRORS WARNINGS PROGRAM_FILES EMITTED UNRESOLVED TOP_CODES
    ERRORS=$(grep -oP '^diagnostics:\s+\K[0-9]+(?= error)' "$LOG" || echo 0)
    WARNINGS=$(grep -oP 'error\(s\), \K[0-9]+(?= warning)' "$LOG" || echo 0)
    PROGRAM_FILES=$(grep -oP 'root, \K[0-9]+(?= in program)' "$LOG" || echo 0)
    EMITTED=$(grep -oP '^emitted: \K[0-9]+' "$LOG" || echo 0)
    UNRESOLVED=$(grep -oP '^unresolved imports: \K[0-9]+' "$LOG" || echo 0)
    TOP_CODES=$(grep -oP '^\s+by code: \K.*' "$LOG" | cut -d',' -f1-6 | sed 's/^ *//' || true)
    [[ -n "$TOP_CODES" ]] || TOP_CODES="-"

    local SELF_MED WALL_MED RSS_MB
    SELF_MED=$(median "${SELF_TIMES[@]}")
    WALL_MED=$(median "${WALL_TIMES[@]}")
    RSS_MB=$(( RSS_MAX_KB / 1024 ))

    # -----------------------------------------------------------------------
    # 4. Report + log.
    # -----------------------------------------------------------------------

    echo
    echo "=== bench-compile-tsc summary ($project) ==="
    echo "xtsc:        $XTSC_REV  (heap $HEAP$( ((NO_EMIT)) && echo ", noEmit" ))"
    echo "input:       tsc $project profile @ $TS_COMMIT8 — $PROGRAM_FILES files in program, $ts_loc LOC"
    echo "compile:     ${SELF_MED} ms self-reported (median of $ITERATIONS), ${WALL_MED} ms wall"
    (( SELF_MED > 0 )) && echo "throughput:  $(( ts_loc * 1000 / SELF_MED )) LOC/s"
    (( RSS_MB > 0 )) && echo "peak RSS:    ${RSS_MB} MB"
    echo "diagnostics: $ERRORS error(s), $WARNINGS warning(s)  [real tsc: 0 — every error is xtsc FP/gap]"
    echo "  top codes: $TOP_CODES"
    (( NO_EMIT )) || echo "emitted:     $EMITTED file(s)"
    (( UNRESOLVED > 0 )) && echo "unresolved:  $UNRESOLVED import specifier(s)"
    echo "full output: $LOG"

    if [[ $DO_LOG -eq 1 ]]; then
        mkdir -p "$RESULTS_DIR"
        local results_tsv
        results_tsv="$(results_tsv_for "$project")"
        if [[ ! -f "$results_tsv" ]]; then
            printf '#%s\n' "utc	xtsc_rev	ts_commit	iters	self_ms	wall_ms	rss_mb	files	loc	emitted	errors	warnings	top_codes	heap	label" > "$results_tsv"
        fi
        # Show the previous row for an at-a-glance delta before appending.
        local PREV PREV_SELF PREV_ERR PREV_REV DELTA
        PREV="$(grep -v '^#' "$results_tsv" | tail -1 || true)"
        if [[ -n "$PREV" ]]; then
            PREV_SELF="$(cut -f5 <<<"$PREV")"; PREV_ERR="$(cut -f11 <<<"$PREV")"
            PREV_REV="$(cut -f2 <<<"$PREV")"
            if [[ "$PREV_SELF" =~ ^[0-9]+$ ]] && (( PREV_SELF > 0 )); then
                DELTA=$(awk -v a="$SELF_MED" -v b="$PREV_SELF" 'BEGIN{printf "%+.1f", (a-b)*100.0/b}')
                echo "vs previous: self ${SELF_MED} ms vs ${PREV_SELF} ms (${DELTA}%), errors $ERRORS vs $PREV_ERR  (prev @ $PREV_REV)"
            fi
        fi
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$RUN_STAMP" "$XTSC_REV" "$TS_COMMIT8" "$ITERATIONS" "$SELF_MED" "$WALL_MED" \
            "$RSS_MB" "$PROGRAM_FILES" "$ts_loc" "$EMITTED" "$ERRORS" "$WARNINGS" \
            "$TOP_CODES" "$HEAP" "${LABEL:--}" >> "$results_tsv"
        echo "logged to:   $results_tsv"
    fi

    SUMMARY_ROWS+=("$(printf '%-22s %8s ms %7s LOC/s %6s MB %8s errors  %s' \
        "$project" "$SELF_MED" "$(( SELF_MED > 0 ? ts_loc * 1000 / SELF_MED : 0 ))" \
        "$RSS_MB" "$ERRORS" "$TOP_CODES")")
}

for P in "${PROJECTS[@]}"; do
    bench_project "$P"
done

if (( ${#PROJECTS[@]} > 1 )); then
    echo
    echo "=== project corpus overview ($XTSC_REV) ==="
    printf '%s\n' "${SUMMARY_ROWS[@]}"
fi
