#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2026 Kazimierz Pogoda / Xemantic
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-xtsc-output-exception
#
"""(WARM.22) round 875 — inject the ReachCensus counters into the INV.4 reach
classifiers, and generate the `ReachCensus` object's id table from the SAME
scan, so the two can never drift.

The classifiers share one shape (round 875 § 2): a nodeId-keyed memo probe, an
ANCESTOR ascent that stops at the first memoized/terminal ancestor, and a
FOLD-DOWN that evaluates one EDGE predicate per chain element and memoizes each
result. Two anchors are therefore enough and both are unique per function:

  * the signature line              -> `calls`   (every consultation)
  * the trailing `chain.clear()`    -> `misses` + `folds` (chain.size)
    immediately before a `return`

`calls - misses` is the memo HIT population and `folds` is the number of edge
evaluations, which is the quantity a design change acts on.

`--check` verifies the tree is already instrumented; `--revert` is `git
checkout` (never run it on a tree with uncommitted work — CLAUDE.md round 789).
"""
import re
import subprocess
import sys

CHECKER = "xemantic-typescript-compiler-core/src/commonMain/kotlin/Checker.kt"
SIG_RE = re.compile(r"    private fun (spine[A-Za-z0-9]*(?:Status|Reached|Checked))\(node: Node\)")
SUFFIXES = ("Status", "Reached", "Checked")


def short(fn: str) -> str:
    s = fn[len("spine"):]
    for suf in SUFFIXES:
        if s.endswith(suf):
            return s[: -len(suf)]
    return s


def scan(lines):
    out = []
    for i, l in enumerate(lines):
        m = SIG_RE.match(l)
        if m:
            out.append((m.group(1), i))
    return out


def main() -> None:
    src = open(CHECKER, errors="replace").read()
    lines = src.split("\n")
    sigs = scan(lines)
    names = [short(n) for n, _ in sigs]
    ids = {n: i for i, n in enumerate(sorted(names))}

    if "--ids" in sys.argv:
        print("    // generated by scripts/round875_instrument.py --ids")
        for n in sorted(names):
            print(f"    const val {n.upper()} = {ids[n]}")
        print()
        print("    val names = arrayOf(")
        for n in sorted(names):
            print(f'        "{n}",')
        print("    )")
        return

    if "--check" in sys.argv:
        n = src.count("ReachCensus.calls[")
        print(f"{n} call sites instrumented, {len(sigs)} classifiers found")
        sys.exit(0 if n == len(sigs) else 1)

    if "--revert" in sys.argv:
        subprocess.check_call(["git", "checkout", "--", CHECKER])
        print("reverted")
        return

    if "ReachCensus.calls[" in src:
        sys.exit("REFUSED: already instrumented")

    out = []
    done_calls, done_folds = 0, 0
    i = 0
    sig_at = {idx: fn for fn, idx in sigs}
    # a classifier's tail anchor is the LAST `chain.clear()` before the next
    # top-level `}` of that function, immediately followed by a `return`.
    while i < len(lines):
        line = lines[i]
        out.append(line)
        if i in sig_at:
            fn = sig_at[i]
            key = short(fn).upper()
            out.append(f"        if (ReachCensus.on) ReachCensus.calls[ReachCensus.{key}]++")
            done_calls += 1
            # find this function's tail anchor within its body
            j = i + 1
            tail = None
            while j < len(lines) and not lines[j].startswith("    private fun ") \
                    and not lines[j].startswith("    fun "):
                if lines[j].strip() == "chain.clear()" and lines[j + 1].strip().startswith("return "):
                    tail = j
                if lines[j].strip() == "chain.clear()" and \
                        lines[j + 1].strip().startswith("FrontEnd.addTavHops"):
                    tail = j
                j += 1
            if tail is not None:
                # emit up to and including the tail, injecting BEFORE it
                for k in range(i + 1, tail):
                    out.append(lines[k])
                out.append(
                    f"        if (ReachCensus.on) {{ ReachCensus.misses[ReachCensus.{key}]++; "
                    f"ReachCensus.folds[ReachCensus.{key}] += chain.size.toLong() }}"
                )
                out.append(lines[tail])
                done_folds += 1
                i = tail + 1
                continue
        i += 1

    open(CHECKER, "w").write("\n".join(out))
    print(f"instrumented {done_calls} classifiers ({done_folds} with fold counters)")


if __name__ == "__main__":
    main()
